package com.bsecure.scsm_mobile.common;

public class Paths {

    //public static final String base = "https://bsecuresoftechsolutions.com/scs/";
    public static final String base = "https://gogosmartschool.com/scs/";
   // public static final String base = "https://bsecuresoftechsolutions.com/scs/prod/";
    public static final String member_verify = base + "member_login";
    public static final String member_register = base + "member_register";
    public static final String get_tutor = base + "get_tutor";
    public static final String get_tutor_students =  base + "get_tutor_students";
    public static final String view_tutors = base + "view_tutors";
    public static final String get_transport = base + "get_transport";
    public static final String get_staff = base + "get_staff";
    public static final String get_teacher = base + "get_teacher";
    public static final String get_students = base + "get_students";
    public static final String get_parent_students = base + "get_parent_students";
    public static final String view_attendance = base + "view_attendance";
    public static final String view_marks = base + "view_marks";
    public static final String add_attendance = base + "add_attendance";
    public static final String edit_attendance = base + "edit_attendance";
    public static final String get_examinations = base + "get_examinations";
    public static final String view_syllabus = base + "view_syllabus";
    public static final String get_examination_time_table = base + "get_examination_time_table";
    public static final String add_marks = base + "add_marks";
    public static final String edit_marks = base + "edit_marks";
    public static final String add_syllabus = base + "add_syllabus_android";
    public static final String edit_syllabus = base + "edit_syllabus";
    public static final String send_message = base + "send_student_message";
    public static final String send_message2 = base + "send_class_updates";
    public static final String reply_message = base + "reply_message";
    public static final String forward_message = base + "forward_message";
    public static final String reply_to_all_message = base + "reply_to_all_message";
    public static final String get_members = base + "get_members";
    public static final String up_load = base + "assets/upload/avatar/";
    public static final String add_transport = base + "add_transport";
    public static final String delete_transport = base + "delete_transport";
    public static final String set_transport_status = base + "set_transport_status";
    public static final String add_tutor = base + "add_tutor_v1";
    public static final String edit_tutor = base + "edit_tutor";
    public static final String delete_tutor = base + "delete_tutor_v1";
    public static final String set_tutor_status = base + "set_tutor_status";
    public static final String view_transport_location = base + "view_transport_location";
    public static final String get_coordinates = base + "get_coordinates";
    public static final String attendance_reply = base + "attendance_reply";
    public static final String forward = base + "forward_v1";
    public static final String previous_subject_wise_marks = base + "previous_subject_wise_marks";
    public static final String view_periods = base + "view_periods";
    public static final String check_holiday = base + "check_holiday";
    public static final String check_prformance = base + "check_student_performance";
    public static final String tutor_delete_student = base + "delete_tutor_student_v1";
}
